#!/usr/bin/env bash
set -euo pipefail
here="$(dirname "$0")"

# $ISO: Path to an .iso to boot
: "${ISO:=${here}/build/hello-os.iso}"

# $STUB_ISO: Path to an .iso that only contains GRUB
: "${STUB_ISO:=}"

qemu_args=(
	-s
	-boot d
)

if [[ -n "${STUB_ISO}" ]]; then
	# The .iso only contains GRUB and loads the kernel from the second
	# disk generated by QEMU
	qemu_args+=(
		-cdrom "${STUB_ISO}"
		-drive "file=fat:rw:${here}/build,format=raw,media=disk"
	)
else
	qemu_args+=(
		-cdrom "${ISO}"
	)
fi

exec qemu-system-x86_64 "${qemu_args[@]}" "$@"
